/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Telas.Cadastros.Cad_Estrutura;
import Telas.Cadastros.Cad_Fornecedor;
import Telas.Cadastros.Cad_GrupoProduto;
import Telas.Cadastros.Cad_Produto;
import Telas.Consultas.Cons_Produto;

/**
 *
 * @author cemancini
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
        //Maximizando:
        this.setExtendedState(this.getExtendedState() | MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGrupoProduto = new javax.swing.JButton();
        BtnFornecedor = new javax.swing.JButton();
        BtnProduto = new javax.swing.JButton();
        BtnEstrutura = new javax.swing.JButton();
        BtnConsPro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Custos");

        BtnGrupoProduto.setText("Grupos de Produtos");
        BtnGrupoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGrupoProdutoActionPerformed(evt);
            }
        });

        BtnFornecedor.setText("Fornecedores");
        BtnFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFornecedorActionPerformed(evt);
            }
        });

        BtnProduto.setText("Produtos");
        BtnProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProdutoActionPerformed(evt);
            }
        });

        BtnEstrutura.setText("Estrutura");
        BtnEstrutura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEstruturaActionPerformed(evt);
            }
        });

        BtnConsPro.setText("Consulta Produto");
        BtnConsPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsProActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BtnConsPro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(BtnEstrutura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnGrupoProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnFornecedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(496, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnGrupoProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnFornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnEstrutura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnConsPro)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGrupoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGrupoProdutoActionPerformed
        Cad_GrupoProduto tela = Cad_GrupoProduto.getInstance();
        tela.setVisible(true);
        tela.setExtendedState(this.getExtendedState() | MAXIMIZED_BOTH);
    }//GEN-LAST:event_BtnGrupoProdutoActionPerformed

    private void BtnFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFornecedorActionPerformed
        Cad_Fornecedor tela = Cad_Fornecedor.getInstance();
        tela.setVisible(true);
        tela.setExtendedState(this.getExtendedState() | MAXIMIZED_BOTH);
    }//GEN-LAST:event_BtnFornecedorActionPerformed

    private void BtnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProdutoActionPerformed
        Cad_Produto tela = Cad_Produto.getInstance();
        tela.AtualizaCombos();
        tela.setVisible(true);
        tela.setExtendedState(this.getExtendedState() | MAXIMIZED_BOTH);
    }//GEN-LAST:event_BtnProdutoActionPerformed

    private void BtnEstruturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEstruturaActionPerformed
        Cad_Estrutura tela = Cad_Estrutura.getInstance();
        tela.setVisible(true);
        tela.setExtendedState(this.getExtendedState() | MAXIMIZED_BOTH);
    }//GEN-LAST:event_BtnEstruturaActionPerformed

    private void BtnConsProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsProActionPerformed
        Cons_Produto tela = Cons_Produto.getInstance();
        tela.AtualizaCombos();
        tela.setVisible(true);
        tela.setExtendedState(this.getExtendedState() | MAXIMIZED_BOTH);
    }//GEN-LAST:event_BtnConsProActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConsPro;
    private javax.swing.JButton BtnEstrutura;
    private javax.swing.JButton BtnFornecedor;
    private javax.swing.JButton BtnGrupoProduto;
    private javax.swing.JButton BtnProduto;
    // End of variables declaration//GEN-END:variables
}
