/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas.Cadastros;

import Tabelas.GrupoProduto;
import Util.HibernateUtil;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.criterion.Restrictions;

/**
 *
 * @author cemancini
 */
public class Cad_GrupoProduto extends javax.swing.JFrame {
    
    private static Cad_GrupoProduto instance = null;
    private Long id;
    Session conexao;
    Transaction tx;

    /**
     * Creates new form GrupoProduto
     */
    public Cad_GrupoProduto() {
        initComponents();
        id = -1L;
        habilitarCamposCadastro(false);
        TxtCodigo.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, Collections.EMPTY_SET); 
    }
    
    public static Cad_GrupoProduto getInstance() {
      if (instance == null)
         instance = new Cad_GrupoProduto();
      return instance;
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        TxtDescricao = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        LblDescricao = new javax.swing.JLabel();
        TxtCodigo = new javax.swing.JTextField();
        BtnInserirAlterar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        BtnExcluir = new javax.swing.JButton();
        BtnSair = new javax.swing.JButton();
        BtnPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de Grupos de Produtos");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Código:");

        TxtDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxtDescricao.setNextFocusableComponent(BtnInserirAlterar);

        LblDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblDescricao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblDescricao.setText("Descrição:");

        TxtCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxtCodigo.setNextFocusableComponent(TxtDescricao);
        TxtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCodigoKeyTyped(evt);
            }
        });

        BtnInserirAlterar.setText("Inserir");
        BtnInserirAlterar.setEnabled(false);
        BtnInserirAlterar.setNextFocusableComponent(BtnCancelar);
        BtnInserirAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInserirAlterarActionPerformed(evt);
            }
        });

        BtnCancelar.setText("Cancelar");
        BtnCancelar.setEnabled(false);
        BtnCancelar.setNextFocusableComponent(BtnExcluir);
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        BtnExcluir.setText("Excluir");
        BtnExcluir.setEnabled(false);
        BtnExcluir.setNextFocusableComponent(BtnSair);
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });

        BtnSair.setText("Sair");
        BtnSair.setNextFocusableComponent(TxtCodigo);
        BtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSairActionPerformed(evt);
            }
        });

        BtnPesquisar.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnPesquisar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LblDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 12, Short.MAX_VALUE))
                            .addComponent(jSeparator2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnInserirAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtnInserirAlterar)
                        .addComponent(BtnPesquisar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblDescricao)
                            .addComponent(TxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnExcluir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnSair)
                .addContainerGap(410, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSairActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Tem certeza que deseja sair?", "Confirmação", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            limparCampos();
            habilitarCamposCadastro(false);
            BtnExcluir.setEnabled(false);
            this.dispose();
        }
    }//GEN-LAST:event_BtnSairActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Tem certeza que deseja cancelar?", "Confirmação", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            limparCampos();
            habilitarCamposCadastro(false);
            BtnExcluir.setEnabled(false);
            id = -1L;
        }
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void TxtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCodigoKeyTyped
        if(evt.getKeyChar()== KeyEvent.VK_ENTER || evt.getKeyChar() == KeyEvent.VK_TAB){
            if(!TxtCodigo.getText().isEmpty()){
                habilitarCamposCadastro(true);
                
                //TODO: Pesquisar grupo existente para trazer descrição preenchida
                try {
                    conexao = HibernateUtil.openSession();
                    
                    Criteria crit = conexao.createCriteria(GrupoProduto.class);
                    crit.add(Restrictions.eq("Codigo", TxtCodigo.getText()));
                    List results = crit.list();
                    if(results.size() > 0){
                        BtnInserirAlterar.setText("Alterar");
                        BtnExcluir.setEnabled(true);
                        GrupoProduto grupo = (GrupoProduto) results.get(0);
                        TxtDescricao.setText(grupo.getDescricao());
                        id = grupo.getID();
                    } else{
                        BtnInserirAlterar.setText("Inserir");
                        BtnExcluir.setEnabled(false);
                        TxtDescricao.setText("");
                        id = -1L;
                    }
                } catch(Exception ex){
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Operação mal sucedida. Motivo: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                } 
                
                TxtDescricao.requestFocusInWindow();
                BtnInserirAlterar.setEnabled(true);
                BtnCancelar.setEnabled(true);
                
            } else{
                JOptionPane.showMessageDialog(this, "O campo de Código não deve ficar vazio!", "Erro", JOptionPane.OK_OPTION);
                TxtCodigo.requestFocusInWindow();
            }
        } else if(evt.getKeyChar() == KeyEvent.VK_BACK_SPACE){
            if(TxtCodigo.getText().isEmpty()){
                limparCampos();
                habilitarCamposCadastro(false);
            }
        }
    }//GEN-LAST:event_TxtCodigoKeyTyped

    private void BtnInserirAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInserirAlterarActionPerformed
        if(TxtDescricao.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "O campo de Descrição não deve ficar vazio!", "Erro", JOptionPane.OK_OPTION);
            TxtDescricao.requestFocusInWindow();
        } else{
            // Abrindo conexão:
            conexao = HibernateUtil.openSession();
            tx = conexao.beginTransaction();
            
            GrupoProduto grupo = new GrupoProduto();
            if(id != -1L)
                grupo.setID(id);
            grupo.setCodigo(TxtCodigo.getText());
            grupo.setDescricao(TxtDescricao.getText());
            
            // Persistindo objeto:
            try {
                conexao.saveOrUpdate(grupo);
                tx.commit();
                TxtCodigo.requestFocusInWindow();
                TxtCodigo.selectAll();
                BtnExcluir.setEnabled(true);
                habilitarCamposCadastro(false);
                id = grupo.getID();
                
            } catch(Exception ex){
                tx.rollback();
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Operação mal sucedida. Motivo: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
            conexao.close();
        }
    }//GEN-LAST:event_BtnInserirAlterarActionPerformed

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir?", "Confirmação", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            conexao = HibernateUtil.openSession();
            tx = conexao.beginTransaction();
            
            // TODO: Checar se existe produto ligado ao grupo
            
            GrupoProduto grupo = (GrupoProduto) conexao.get(GrupoProduto.class, id);
            
            try {
                if(grupo != null){
                    conexao.delete(grupo);
                    tx.commit();
                } else{
                    JOptionPane.showMessageDialog(this, "Impossível excluir. Grupo não encontrado", "Erro", JOptionPane.ERROR_MESSAGE);
                }
                limparCampos();
                habilitarCamposCadastro(false);
                BtnExcluir.setEnabled(false);
            } catch(Exception ex){
                tx.rollback();
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Operação mal sucedida. Motivo: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BtnExcluirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        limparCampos();
        habilitarCamposCadastro(false);
        BtnExcluir.setEnabled(false);
    }//GEN-LAST:event_formWindowClosing

    private void limparCampos(){
        TxtCodigo.setText("");
        TxtDescricao.setText("");
        TxtCodigo.requestFocusInWindow();
        BtnInserirAlterar.setEnabled(false);
        BtnInserirAlterar.setText("Inserir");
        BtnCancelar.setEnabled(false);
    }
    
    private void habilitarCamposCadastro(boolean valor){
        LblDescricao.setEnabled(valor);
        TxtDescricao.setEnabled(valor);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cad_GrupoProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cad_GrupoProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cad_GrupoProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cad_GrupoProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cad_GrupoProduto().setVisible(true);
         
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnInserirAlterar;
    private javax.swing.JButton BtnPesquisar;
    private javax.swing.JButton BtnSair;
    private javax.swing.JLabel LblDescricao;
    private javax.swing.JTextField TxtCodigo;
    private javax.swing.JTextField TxtDescricao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
