/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas.Cadastros;

import Tabelas.Fornecedor;
import Tabelas.GrupoProduto;
import Tabelas.Produto;
import Telas.Consultas.ConsExis_Produto;
import Util.HibernateUtil;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.criterion.Order;
import org.hibernate.criterion.Restrictions;

/**
 *
 * @author cemancini
 */
public class Cad_Produto extends javax.swing.JFrame {
    private static Cad_Produto instance = null;
    private Long id;
    Session conexao;
    Transaction tx;
    /**
     * Creates new form Cad_Produto
     */
    public Cad_Produto() {
        initComponents();
        id = -1L;
        limparCampos();
        habilitarCamposCadastro(false);
        TxtCodigo.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, Collections.EMPTY_SET); 
    }

    public static Cad_Produto getInstance() {
        if (instance == null)
           instance = new Cad_Produto();
        return instance;
    }
    
    public void AtualizaCombos(){
        CmbGrupo.removeAllItems();
        CmbFornecedor1.removeAllItems();
        CmbFornecedor2.removeAllItems();
        CmbFornecedor3.removeAllItems();
        
        // Abrindo conexão:
        conexao = HibernateUtil.openSession();
        
        // Buscando e preenchendo grupos:
        Criteria crit = conexao.createCriteria(GrupoProduto.class);
        crit.addOrder(Order.asc("Codigo"));
        List<GrupoProduto> grupos = crit.list();
        CmbGrupo.addItem("Selecione o Grupo");
        for(GrupoProduto grupo : grupos){
            CmbGrupo.addItem(grupo.getCodigo());
        }
        
        // Buscando e preenchendo fornecedores:
        crit = conexao.createCriteria(Fornecedor.class);
        crit.addOrder(Order.asc("Codigo"));
        List<Fornecedor> fornecedores = crit.list();
        CmbFornecedor1.addItem("Selecione o Fornecedor 1");
        CmbFornecedor2.addItem("Selecione o Fornecedor 2");
        CmbFornecedor3.addItem("Selecione o Fornecedor 3");
        for(Fornecedor fornecedor : fornecedores){
            CmbFornecedor1.addItem(fornecedor.getCodigo());
            CmbFornecedor2.addItem(fornecedor.getCodigo());
            CmbFornecedor3.addItem(fornecedor.getCodigo());
        }
        
        // Fechando conexão:
        conexao.close();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPane1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        LblCodigo = new javax.swing.JLabel();
        TxtCodigo = new javax.swing.JTextField();
        BtnPesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtnInserirAlterar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        BtnExcluir = new javax.swing.JButton();
        BtnSair = new javax.swing.JButton();
        LblDescricao = new javax.swing.JLabel();
        TxtDescricao = new javax.swing.JTextField();
        LblGrupo = new javax.swing.JLabel();
        CmbGrupo = new javax.swing.JComboBox<>();
        LblFornec1 = new javax.swing.JLabel();
        CmbFornecedor1 = new javax.swing.JComboBox<>();
        CmbFornecedor2 = new javax.swing.JComboBox<>();
        LblFornec2 = new javax.swing.JLabel();
        CmbFornecedor3 = new javax.swing.JComboBox<>();
        LblFornec3 = new javax.swing.JLabel();
        LblUniMed = new javax.swing.JLabel();
        CmbUniMed = new javax.swing.JComboBox<>();
        LblAtivo = new javax.swing.JLabel();
        ChkAtivo = new javax.swing.JCheckBox();
        LblPrecoVenda = new javax.swing.JLabel();
        FTxtPrecoVenda = new javax.swing.JFormattedTextField();
        LblPrecoCusto = new javax.swing.JLabel();
        FTxtPrecoCusto = new javax.swing.JFormattedTextField();
        LblDevVendas = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        FTxtDevVendas = new javax.swing.JFormattedTextField();
        LblAbatVendas = new javax.swing.JLabel();
        FTxtAbatVendas = new javax.swing.JFormattedTextField();
        LblComisVendas = new javax.swing.JLabel();
        FTxtComVendas = new javax.swing.JFormattedTextField();
        LblIcms = new javax.swing.JLabel();
        FTxtIcmsVendas = new javax.swing.JFormattedTextField();
        LblIpi = new javax.swing.JLabel();
        FTxtIpiVendas = new javax.swing.JFormattedTextField();
        LblPis = new javax.swing.JLabel();
        FTxtPisVendas = new javax.swing.JFormattedTextField();
        LblCofins = new javax.swing.JLabel();
        FTxtCofinsVendas = new javax.swing.JFormattedTextField();
        LblSimples = new javax.swing.JLabel();
        FTxtSimplesVendas = new javax.swing.JFormattedTextField();
        FTxtIssVendas = new javax.swing.JFormattedTextField();
        LblIss = new javax.swing.JLabel();
        FTxtIrVendas = new javax.swing.JFormattedTextField();
        LblIr = new javax.swing.JLabel();
        FTxtCsllVendas = new javax.swing.JFormattedTextField();
        LblCsll = new javax.swing.JLabel();
        LblEmbalagem = new javax.swing.JLabel();
        LblFrete = new javax.swing.JLabel();
        FTxtEmbalagem = new javax.swing.JFormattedTextField();
        FTxtFrete = new javax.swing.JFormattedTextField();
        LblInsumos = new javax.swing.JLabel();
        FTxtOutrosInsumos = new javax.swing.JFormattedTextField();
        FTxtMargemContrib = new javax.swing.JFormattedTextField();
        LblNcm = new javax.swing.JLabel();
        TxtNcm = new javax.swing.JTextField();
        LblMargem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produtos");

        LblCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblCodigo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblCodigo.setText("Código:");

        TxtCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCodigoKeyTyped(evt);
            }
        });

        BtnPesquisar.setText("...");
        BtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesquisarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de Produtos");

        BtnInserirAlterar.setText("Inserir");
        BtnInserirAlterar.setEnabled(false);
        BtnInserirAlterar.setNextFocusableComponent(BtnCancelar);
        BtnInserirAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInserirAlterarActionPerformed(evt);
            }
        });

        BtnCancelar.setText("Cancelar");
        BtnCancelar.setEnabled(false);
        BtnCancelar.setNextFocusableComponent(BtnExcluir);
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        BtnExcluir.setText("Excluir");
        BtnExcluir.setEnabled(false);
        BtnExcluir.setNextFocusableComponent(BtnSair);
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });

        BtnSair.setText("Sair");
        BtnSair.setNextFocusableComponent(TxtDescricao);
        BtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSairActionPerformed(evt);
            }
        });

        LblDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblDescricao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblDescricao.setText("Descrição:");

        TxtDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxtDescricao.setNextFocusableComponent(CmbGrupo);

        LblGrupo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblGrupo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblGrupo.setText("Grupo:");

        CmbGrupo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CmbGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CmbGrupo.setNextFocusableComponent(CmbFornecedor1);

        LblFornec1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblFornec1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblFornec1.setText("Fornecedor 1:");

        CmbFornecedor1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CmbFornecedor1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CmbFornecedor1.setNextFocusableComponent(CmbFornecedor2);

        CmbFornecedor2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CmbFornecedor2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CmbFornecedor2.setNextFocusableComponent(CmbFornecedor3);

        LblFornec2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblFornec2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblFornec2.setText("Fornecedor 2:");

        CmbFornecedor3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CmbFornecedor3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CmbFornecedor3.setNextFocusableComponent(CmbUniMed);

        LblFornec3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblFornec3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblFornec3.setText("Fornecedor 3:");

        LblUniMed.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblUniMed.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblUniMed.setText("Unidade de Medida:");

        CmbUniMed.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CmbUniMed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PC", "KG" }));
        CmbUniMed.setNextFocusableComponent(ChkAtivo);

        LblAtivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblAtivo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblAtivo.setText("Ativo:");

        ChkAtivo.setNextFocusableComponent(FTxtPrecoVenda);

        LblPrecoVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblPrecoVenda.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblPrecoVenda.setText("Preço Venda (R$):");

        FTxtPrecoVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        FTxtPrecoVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FTxtPrecoVenda.setNextFocusableComponent(FTxtPrecoCusto);

        LblPrecoCusto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblPrecoCusto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblPrecoCusto.setText("Preço Custo (R$):");

        FTxtPrecoCusto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        FTxtPrecoCusto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FTxtPrecoCusto.setNextFocusableComponent(FTxtDevVendas);

        LblDevVendas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblDevVendas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblDevVendas.setText("Devoluções Vendas (%):");

        FTxtDevVendas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        FTxtDevVendas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FTxtDevVendas.setNextFocusableComponent(FTxtAbatVendas);

        LblAbatVendas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblAbatVendas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblAbatVendas.setText("Abatimentos Vendas (%):");

        FTxtAbatVendas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        FTxtAbatVendas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FTxtAbatVendas.setNextFocusableComponent(FTxtComVendas);

        LblComisVendas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblComisVendas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblComisVendas.setText("Comissões Vendas (%):");

        FTxtComVendas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        FTxtComVendas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FTxtComVendas.setNextFocusableComponent(FTxtIcmsVendas);

        LblIcms.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblIcms.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblIcms.setText("ICMS Vendas (%):");

        FTxtIcmsVendas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        FTxtIcmsVendas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FTxtIcmsVendas.setNextFocusableComponent(FTxtIpiVendas);

        LblIpi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblIpi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblIpi.setText("IPI Vendas (%):");

        FTxtIpiVendas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        FTxtIpiVendas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FTxtIpiVendas.setNextFocusableComponent(FTxtPisVendas);

        LblPis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblPis.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblPis.setText("PIS Vendas (%):");

        FTxtPisVendas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        FTxtPisVendas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FTxtPisVendas.setNextFocusableComponent(FTxtCofinsVendas);

        LblCofins.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblCofins.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblCofins.setText("Cofins Vendas (%):");

        FTxtCofinsVendas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        FTxtCofinsVendas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FTxtCofinsVendas.setNextFocusableComponent(FTxtSimplesVendas);

        LblSimples.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblSimples.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblSimples.setText("Simples Vendas (%):");

        FTxtSimplesVendas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        FTxtSimplesVendas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FTxtSimplesVendas.setNextFocusableComponent(FTxtIssVendas);

        FTxtIssVendas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        FTxtIssVendas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FTxtIssVendas.setNextFocusableComponent(FTxtIrVendas);

        LblIss.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblIss.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblIss.setText("ISS Vendas (%):");

        FTxtIrVendas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        FTxtIrVendas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FTxtIrVendas.setNextFocusableComponent(FTxtCsllVendas);

        LblIr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblIr.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblIr.setText("IR Vendas (%):");

        FTxtCsllVendas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        FTxtCsllVendas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FTxtCsllVendas.setNextFocusableComponent(FTxtEmbalagem);

        LblCsll.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblCsll.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblCsll.setText("CSLL Vendas (%):");

        LblEmbalagem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblEmbalagem.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblEmbalagem.setText("Embalagem (%):");

        LblFrete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblFrete.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblFrete.setText("Frete Vendas (%):");

        FTxtEmbalagem.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        FTxtEmbalagem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FTxtEmbalagem.setNextFocusableComponent(FTxtFrete);

        FTxtFrete.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        FTxtFrete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FTxtFrete.setNextFocusableComponent(FTxtOutrosInsumos);

        LblInsumos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblInsumos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblInsumos.setText("Outros Insumos (%):");

        FTxtOutrosInsumos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        FTxtOutrosInsumos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FTxtOutrosInsumos.setNextFocusableComponent(FTxtMargemContrib);

        FTxtMargemContrib.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        FTxtMargemContrib.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FTxtMargemContrib.setNextFocusableComponent(TxtNcm);

        LblNcm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblNcm.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblNcm.setText("NCM:");

        TxtNcm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxtNcm.setNextFocusableComponent(BtnInserirAlterar);

        LblMargem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblMargem.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblMargem.setText("Margem Contrib. (R$):");

        javax.swing.GroupLayout jPane1Layout = new javax.swing.GroupLayout(jPane1);
        jPane1.setLayout(jPane1Layout);
        jPane1Layout.setHorizontalGroup(
            jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPane1Layout.createSequentialGroup()
                        .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPane1Layout.createSequentialGroup()
                                .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPane1Layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(LblPrecoCusto))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(FTxtPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPane1Layout.createSequentialGroup()
                                            .addGap(44, 44, 44)
                                            .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(LblDescricao)
                                                .addComponent(LblPrecoVenda))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(FTxtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPane1Layout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addComponent(LblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnPesquisar))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 136, Short.MAX_VALUE))
                            .addComponent(jSeparator2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnInserirAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPane1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(BtnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BtnExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(BtnSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPane1Layout.createSequentialGroup()
                        .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPane1Layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(LblAtivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ChkAtivo))
                            .addGroup(jPane1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LblGrupo)
                                    .addComponent(LblFornec1)
                                    .addComponent(LblFornec2)
                                    .addComponent(LblFornec3)
                                    .addComponent(LblUniMed))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CmbFornecedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(CmbUniMed, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CmbFornecedor2, 0, 186, Short.MAX_VALUE)
                                        .addComponent(CmbFornecedor3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(TxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CmbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPane1Layout.createSequentialGroup()
                                    .addComponent(LblPis)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(FTxtPisVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPane1Layout.createSequentialGroup()
                                    .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(LblComisVendas)
                                            .addComponent(LblAbatVendas))
                                        .addComponent(LblIcms, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(LblIpi, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(FTxtIpiVendas, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                        .addComponent(FTxtIcmsVendas)
                                        .addComponent(FTxtAbatVendas)
                                        .addComponent(FTxtComVendas)))
                                .addGroup(jPane1Layout.createSequentialGroup()
                                    .addComponent(LblCofins)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(FTxtCofinsVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPane1Layout.createSequentialGroup()
                                    .addComponent(LblSimples)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(FTxtSimplesVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPane1Layout.createSequentialGroup()
                                    .addComponent(LblIss)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(FTxtIssVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPane1Layout.createSequentialGroup()
                                    .addComponent(LblIr)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(FTxtIrVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPane1Layout.createSequentialGroup()
                                    .addComponent(LblCsll)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(FTxtCsllVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPane1Layout.createSequentialGroup()
                                    .addComponent(LblEmbalagem)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(FTxtEmbalagem, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPane1Layout.createSequentialGroup()
                                    .addComponent(LblFrete)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(FTxtFrete, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPane1Layout.createSequentialGroup()
                                    .addComponent(LblInsumos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(FTxtOutrosInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPane1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(LblDevVendas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FTxtDevVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPane1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LblMargem)
                                    .addComponent(LblNcm))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtNcm, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FTxtMargemContrib, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPane1Layout.setVerticalGroup(
            jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPane1Layout.createSequentialGroup()
                        .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnPesquisar)
                            .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LblCodigo)
                                .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblDescricao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblGrupo)
                            .addComponent(CmbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblFornec1)
                            .addComponent(CmbFornecedor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CmbFornecedor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblFornec2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblFornec3)
                            .addComponent(CmbFornecedor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblUniMed)
                            .addComponent(CmbUniMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblAtivo)
                            .addComponent(ChkAtivo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblPrecoVenda)
                            .addComponent(FTxtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FTxtPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblPrecoCusto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblDevVendas)
                            .addComponent(FTxtDevVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblAbatVendas)
                            .addComponent(FTxtAbatVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblComisVendas)
                            .addComponent(FTxtComVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblIcms)
                            .addComponent(FTxtIcmsVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblIpi)
                            .addComponent(FTxtIpiVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblPis)
                            .addComponent(FTxtPisVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblCofins)
                            .addComponent(FTxtCofinsVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblSimples)
                            .addComponent(FTxtSimplesVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblIss)
                            .addComponent(FTxtIssVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblIr)
                            .addComponent(FTxtIrVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblCsll)
                            .addComponent(FTxtCsllVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblEmbalagem)
                            .addComponent(FTxtEmbalagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblFrete)
                            .addComponent(FTxtFrete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblInsumos)
                            .addComponent(FTxtOutrosInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FTxtMargemContrib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblMargem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblNcm)
                            .addComponent(TxtNcm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPane1Layout.createSequentialGroup()
                        .addComponent(BtnInserirAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnSair)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCodigoKeyTyped
        if(evt.getKeyChar()== KeyEvent.VK_ENTER || evt.getKeyChar() == KeyEvent.VK_TAB){
            if(!TxtCodigo.getText().isEmpty()){
                buscar(TxtCodigo.getText());
            } else{
                JOptionPane.showMessageDialog(this, "O campo de Código não deve ficar vazio!", "Erro", JOptionPane.OK_OPTION);
                TxtCodigo.requestFocusInWindow();
            }
        } else if(evt.getKeyChar() == KeyEvent.VK_BACK_SPACE){
            if(TxtCodigo.getText().isEmpty()){
                limparCampos();
                habilitarCamposCadastro(false);
            }
        }
    }//GEN-LAST:event_TxtCodigoKeyTyped

    private void BtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesquisarActionPerformed
        ConsExis_Produto janela = ConsExis_Produto.getInstance();
        janela.setJanelaPai(this, "CAD_PRO");
        janela.alimentarTabela();
        janela.setVisible(true);
    }//GEN-LAST:event_BtnPesquisarActionPerformed

    private void BtnInserirAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInserirAlterarActionPerformed
        if(TxtDescricao.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "O campo de Descrição não deve ficar vazio!", "Erro", JOptionPane.OK_OPTION);
            TxtDescricao.requestFocusInWindow();
        } else{
            // Abrindo conexão:
            conexao = HibernateUtil.openSession();
            tx = conexao.beginTransaction();

            Produto produto = new Produto();
            if(id != -1L)
                produto.setID(id);
            produto.setCodigo(TxtCodigo.getText());
            produto.setDescricao(TxtDescricao.getText());
            
            // Grupo:
            if(CmbGrupo.getSelectedIndex() > 0){
                // Buscar grupo correspondente:
                String codGrupo = CmbGrupo.getSelectedItem().toString();
                Criteria crit = conexao.createCriteria(GrupoProduto.class);
                crit.add(Restrictions.eq("Codigo", codGrupo));
                List results = crit.list();
                if(results.size() > 0){
                    GrupoProduto grupo = (GrupoProduto) results.get(0);
                    produto.setGrupo(grupo);
                }
            } else
                produto.setGrupo(null);
            
            // Fornecedor 1:
            if(CmbFornecedor1.getSelectedIndex() > 0){
                // Buscar grupo correspondente:
                String codFornecedor = CmbFornecedor1.getSelectedItem().toString();
                Criteria crit = conexao.createCriteria(Fornecedor.class);
                crit.add(Restrictions.eq("Codigo", codFornecedor));
                List results = crit.list();
                if(results.size() > 0){
                    Fornecedor fornec = (Fornecedor) results.get(0);
                    produto.setFornecedor1(fornec);
                }
            } else
                produto.setFornecedor1(null);
            
            // Fornecedor 2:
            if(CmbFornecedor2.getSelectedIndex() > 0){
                // Buscar grupo correspondente:
                String codFornecedor = CmbFornecedor2.getSelectedItem().toString();
                Criteria crit = conexao.createCriteria(Fornecedor.class);
                crit.add(Restrictions.eq("Codigo", codFornecedor));
                List results = crit.list();
                if(results.size() > 0){
                    Fornecedor fornec = (Fornecedor) results.get(0);
                    produto.setFornecedor2(fornec);
                }
            } else
                produto.setFornecedor2(null);
            
            // Fornecedor 3:
            if(CmbFornecedor3.getSelectedIndex() > 0){
                // Buscar grupo correspondente:
                String codFornecedor = CmbFornecedor3.getSelectedItem().toString();
                Criteria crit = conexao.createCriteria(Fornecedor.class);
                crit.add(Restrictions.eq("Codigo", codFornecedor));
                List results = crit.list();
                if(results.size() > 0){
                    Fornecedor fornec = (Fornecedor) results.get(0);
                    produto.setFornecedor3(fornec);
                }
            } else
                produto.setFornecedor3(null);
            
            produto.setUnidadeMedida(CmbUniMed.getSelectedItem().toString().replace(',', '.'));
            produto.setAtivo(ChkAtivo.isSelected());
            if(!FTxtPrecoVenda.getText().isEmpty())
                produto.setPrecoVenda(Double.valueOf(FTxtPrecoVenda.getText().replace(',', '.')));
            if(!FTxtPrecoCusto.getText().isEmpty())
                produto.setPrecoCusto(Double.valueOf(FTxtPrecoCusto.getText().replace(',', '.')));
            if(!FTxtDevVendas.getText().isEmpty())
                produto.setDevolucoesVendas(Double.valueOf(FTxtDevVendas.getText().replace(',', '.')));
            if(!FTxtAbatVendas.getText().isEmpty())
                produto.setAbatimentosVendas(Double.valueOf(FTxtAbatVendas.getText().replace(',', '.')));
            if(!FTxtComVendas.getText().isEmpty())
                produto.setComissoesVendas(Double.valueOf(FTxtComVendas.getText().replace(',', '.')));
            if(!FTxtIcmsVendas.getText().isEmpty())
                produto.setIcmsVendas(Double.valueOf(FTxtIcmsVendas.getText().replace(',', '.')));
            if(!FTxtIpiVendas.getText().isEmpty())
                produto.setIpiVendas(Double.valueOf(FTxtIpiVendas.getText().replace(',', '.')));
            if(!FTxtPisVendas.getText().isEmpty())
                produto.setPisVendas(Double.valueOf(FTxtPisVendas.getText().replace(',', '.')));
            if(!FTxtCofinsVendas.getText().isEmpty())
                produto.setCofinsVendas(Double.valueOf(FTxtCofinsVendas.getText().replace(',', '.')));
            if(!FTxtSimplesVendas.getText().isEmpty())
                produto.setSimplesVendas(Double.valueOf(FTxtSimplesVendas.getText().replace(',', '.')));
            if(!FTxtIssVendas.getText().isEmpty())
                produto.setIssVendas(Double.valueOf(FTxtIssVendas.getText().replace(',', '.')));
            if(!FTxtIrVendas.getText().isEmpty())
                produto.setIrVendas(Double.valueOf(FTxtIrVendas.getText().replace(',', '.')));
            if(!FTxtCsllVendas.getText().isEmpty())
                produto.setCsllVendas(Double.valueOf(FTxtCsllVendas.getText().replace(',', '.')));
            if(!FTxtEmbalagem.getText().isEmpty())
                produto.setEmbalagem(Double.valueOf(FTxtEmbalagem.getText().replace(',', '.')));
            if(!FTxtFrete.getText().isEmpty())
                produto.setFreteVendas(Double.valueOf(FTxtFrete.getText().replace(',', '.')));
            if(!FTxtOutrosInsumos.getText().isEmpty())
                produto.setOutrosInsumos(Double.valueOf(FTxtOutrosInsumos.getText().replace(',', '.')));
            if(!FTxtMargemContrib.getText().isEmpty())
                produto.setMargemContrib(Double.valueOf(FTxtMargemContrib.getText().replace(',', '.')));
            if(!TxtNcm.getText().isEmpty())
                produto.setNcm(TxtNcm.getText());

            // Persistindo objeto:
            try {
                conexao.saveOrUpdate(produto);
                tx.commit();
                TxtCodigo.requestFocusInWindow();
                TxtCodigo.selectAll();
                BtnExcluir.setEnabled(true);
                habilitarCamposCadastro(false);
                id = produto.getID();

            } catch(Exception ex){
                tx.rollback();
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Operação mal sucedida. Motivo: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
            conexao.close();
        }
    }//GEN-LAST:event_BtnInserirAlterarActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Tem certeza que deseja cancelar?", "Confirmação", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            limparCampos();
            habilitarCamposCadastro(false);
            BtnExcluir.setEnabled(false);
            id = -1L;
        }
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir?", "Confirmação", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            conexao = HibernateUtil.openSession();
            tx = conexao.beginTransaction();

            Produto produto = (Produto) conexao.get(Produto.class, id);

            // Checando se o produto está ligado a alguma tabela:
            /*
            Criteria crit = conexao.createCriteria(Produto.class);
            Criterion rest1 = Restrictions.eq("Fornecedor1", fornecedor);
            Criterion rest2 = Restrictions.eq("Fornecedor2", fornecedor);
            Criterion rest3 = Restrictions.eq("Fornecedor3", fornecedor);
            crit.add(Restrictions.or(rest1, rest2, rest3));

            List results = crit.list();
            if(results.size() > 0)
            JOptionPane.showMessageDialog(this, "Impossível excluir. Fornecedor ligado a pelo menos um Produto.", "Erro", JOptionPane.ERROR_MESSAGE);
            else{
                try {
                    if(fornecedor != null){
                        conexao.delete(fornecedor);
                        tx.commit();
                    } else
                    JOptionPane.showMessageDialog(this, "Impossível excluir. Fornecedor não encontrado.", "Erro", JOptionPane.ERROR_MESSAGE);
                    limparCampos();
                    habilitarCamposCadastro(false);
                    BtnExcluir.setEnabled(false);
                } catch(Exception ex){
                    tx.rollback();
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Operação mal sucedida. Motivo: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
            */
            try {
                if(produto != null){
                    conexao.delete(produto);
                    tx.commit();
                } else
                JOptionPane.showMessageDialog(this, "Impossível excluir. Produto não encontrado.", "Erro", JOptionPane.ERROR_MESSAGE);
                limparCampos();
                habilitarCamposCadastro(false);
                BtnExcluir.setEnabled(false);
            } catch(Exception ex){
                tx.rollback();
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Operação mal sucedida. Motivo: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BtnExcluirActionPerformed

    private void BtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSairActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Tem certeza que deseja sair?", "Confirmação", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            limparCampos();
            habilitarCamposCadastro(false);
            BtnExcluir.setEnabled(false);
            this.dispose();
        }
    }//GEN-LAST:event_BtnSairActionPerformed

    private void buscar(String codigo){
        habilitarCamposCadastro(true);
        try {
            conexao = HibernateUtil.openSession();
            Criteria crit = conexao.createCriteria(Produto.class);
            crit.add(Restrictions.eq("Codigo", codigo));
            List results = crit.list();
            if(results.size() > 0){
                BtnInserirAlterar.setText("Alterar");
                BtnExcluir.setEnabled(true);
                Produto produto = (Produto) results.get(0);
                TxtDescricao.setText(produto.getDescricao());
                if(produto.getGrupo() != null)
                    CmbGrupo.setSelectedItem(produto.getGrupo().getCodigo());
                else
                    CmbGrupo.setSelectedItem(0);
                if(produto.getFornecedor1()!= null)
                    CmbFornecedor1.setSelectedItem(produto.getFornecedor1().getCodigo());
                else
                    CmbFornecedor1.setSelectedItem(0);
                if(produto.getFornecedor2()!= null)
                    CmbFornecedor2.setSelectedItem(produto.getFornecedor2().getCodigo());
                else
                    CmbFornecedor1.setSelectedItem(0);
                if(produto.getFornecedor3()!= null)
                    CmbFornecedor3.setSelectedItem(produto.getFornecedor3().getCodigo());
                else
                    CmbFornecedor3.setSelectedItem(0);
                CmbUniMed.setSelectedItem(produto.getUnidadeMedida());
                ChkAtivo.setSelected(produto.isAtivo());
                if(produto.getPrecoVenda() != null){
                    FTxtPrecoVenda.setText(produto.getPrecoVenda().toString().replace('.', ','));
                    if(produto.getPrecoVenda() - produto.getPrecoVenda().intValue() == 0)
                        FTxtPrecoVenda.setText(FTxtPrecoVenda.getText() + "0");
                }
                else
                    FTxtPrecoVenda.setText("0,00");
                if(produto.getPrecoCusto() != null){
                    FTxtPrecoCusto.setText(produto.getPrecoCusto().toString().replace('.', ','));
                    if(produto.getPrecoCusto() - produto.getPrecoCusto().intValue() == 0)
                        FTxtPrecoCusto.setText(FTxtPrecoCusto.getText() + "0");
                }
                else
                    FTxtPrecoCusto.setText("0,00");
                if(produto.getDevolucoesVendas()!= null)
                    FTxtDevVendas.setText(produto.getDevolucoesVendas().toString().replace('.', ','));
                else
                    FTxtDevVendas.setText("0,00");
                if(produto.getAbatimentosVendas()!= null)
                    FTxtAbatVendas.setText(produto.getAbatimentosVendas().toString().replace('.', ','));
                else
                    FTxtAbatVendas.setText("0,00");
                if(produto.getComissoesVendas()!= null)
                    FTxtComVendas.setText(produto.getComissoesVendas().toString().replace('.', ','));
                else
                    FTxtComVendas.setText("0,00");
                if(produto.getIcmsVendas()!= null)
                    FTxtIcmsVendas.setText(produto.getIcmsVendas().toString().replace('.', ','));
                else
                    FTxtIcmsVendas.setText("0,00");
                if(produto.getIpiVendas()!= null)
                    FTxtIpiVendas.setText(produto.getIpiVendas().toString().replace('.', ','));
                else
                    FTxtIpiVendas.setText("0,00");
                if(produto.getPisVendas()!= null)
                    FTxtPisVendas.setText(produto.getPisVendas().toString().replace('.', ','));
                else
                    FTxtPisVendas.setText("0,00");
                if(produto.getCofinsVendas()!= null)
                    FTxtCofinsVendas.setText(produto.getCofinsVendas().toString().replace('.', ','));
                else
                    FTxtCofinsVendas.setText("0,00");
                if(produto.getSimplesVendas()!= null)
                    FTxtSimplesVendas.setText(produto.getSimplesVendas().toString().replace('.', ','));
                else
                    FTxtSimplesVendas.setText("0,00");
                if(produto.getIssVendas()!= null)
                    FTxtIssVendas.setText(produto.getIssVendas().toString().replace('.', ','));
                else
                    FTxtIssVendas.setText("0,00");
                if(produto.getIrVendas()!= null)
                    FTxtIrVendas.setText(produto.getIrVendas().toString().replace('.', ','));
                else
                    FTxtIrVendas.setText("0,00");
                if(produto.getCsllVendas()!= null)
                    FTxtCsllVendas.setText(produto.getCsllVendas().toString().replace('.', ','));
                else
                    FTxtCsllVendas.setText("0,00");
                if(produto.getEmbalagem() != null)
                    FTxtEmbalagem.setText(produto.getEmbalagem().toString().replace('.', ','));
                else
                    FTxtEmbalagem.setText("0,00");
                if(produto.getFreteVendas()!= null)
                    FTxtFrete.setText(produto.getFreteVendas().toString().replace('.', ','));
                else
                    FTxtFrete.setText("0,00");
                if(produto.getOutrosInsumos() != null)
                    FTxtOutrosInsumos.setText(produto.getOutrosInsumos().toString().replace('.', ','));
                else
                    FTxtOutrosInsumos.setText("0,00");
                if(produto.getMargemContrib()!= null){
                    FTxtMargemContrib.setText(produto.getMargemContrib().toString().replace('.', ','));
                    if(produto.getMargemContrib() - produto.getMargemContrib().intValue() == 0)
                        FTxtMargemContrib.setText(FTxtMargemContrib.getText() + "0");
                }
                else
                    FTxtMargemContrib.setText("0,00");
                TxtNcm.setText(produto.getNcm());
                id = produto.getID();
            } else{
                BtnInserirAlterar.setText("Inserir");
                BtnExcluir.setEnabled(false);
                TxtDescricao.setText("");
                CmbGrupo.setSelectedIndex(0);
                CmbFornecedor1.setSelectedIndex(0);
                CmbFornecedor2.setSelectedIndex(0);
                CmbFornecedor3.setSelectedIndex(0);
                CmbUniMed.setSelectedIndex(0);
                ChkAtivo.setSelected(false);
                FTxtPrecoVenda.setText("0,00");
                FTxtPrecoCusto.setText("0,00");
                FTxtDevVendas.setText("0,00");
                FTxtAbatVendas.setText("0,00");
                FTxtComVendas.setText("0,00");
                FTxtIcmsVendas.setText("0,00");
                FTxtIpiVendas.setText("0,00");
                FTxtPisVendas.setText("0,00");
                FTxtCofinsVendas.setText("0,00");
                FTxtSimplesVendas.setText("0,00");
                FTxtIssVendas.setText("0,00");
                FTxtIrVendas.setText("0,00");
                FTxtCsllVendas.setText("0,00");
                FTxtEmbalagem.setText("0,00");
                FTxtFrete.setText("0,00");
                FTxtOutrosInsumos.setText("0,00");
                FTxtMargemContrib.setText("0,00");
                TxtNcm.setText("");
                id = -1L;
            }
        } catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Operação mal sucedida. Motivo: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        } 
        conexao.close();
        TxtDescricao.requestFocusInWindow();
        BtnInserirAlterar.setEnabled(true);
        BtnCancelar.setEnabled(true);
    }
    
    public void preencherCampos(String codigo){
        TxtCodigo.setText(codigo);
        buscar(codigo);
    }
    
    private void limparCampos(){
        TxtCodigo.setText("");
        TxtDescricao.setText("");
        CmbGrupo.setSelectedItem(0);
        CmbFornecedor1.setSelectedItem(0);
        CmbFornecedor2.setSelectedItem(0);
        CmbFornecedor3.setSelectedItem(0);
        CmbUniMed.setSelectedItem(0);
        ChkAtivo.setSelected(false);
        FTxtPrecoVenda.setText("0,00");
        FTxtPrecoCusto.setText("0,00");
        FTxtDevVendas.setText("0,00");
        FTxtAbatVendas.setText("0,00");
        FTxtComVendas.setText("0,00");
        FTxtIcmsVendas.setText("0,00");
        FTxtIpiVendas.setText("0,00");
        FTxtPisVendas.setText("0,00");
        FTxtCofinsVendas.setText("0,00");
        FTxtSimplesVendas.setText("0,00");
        FTxtIssVendas.setText("0,00");
        FTxtIrVendas.setText("0,00");
        FTxtCsllVendas.setText("0,00");
        FTxtEmbalagem.setText("0,00");
        FTxtFrete.setText("0,00");
        FTxtOutrosInsumos.setText("0,00");
        FTxtMargemContrib.setText("0,00");
        TxtNcm.setText("");
        TxtCodigo.requestFocusInWindow();
        BtnInserirAlterar.setEnabled(false);
        BtnInserirAlterar.setText("Inserir");
        BtnCancelar.setEnabled(false);
    }
    
    private void habilitarCamposCadastro(boolean valor){
        LblDescricao.setEnabled(valor);
        TxtDescricao.setEnabled(valor);
        LblGrupo.setEnabled(valor);
        CmbGrupo.setEnabled(valor);
        LblFornec1.setEnabled(valor);
        CmbFornecedor1.setEnabled(valor);
        LblFornec2.setEnabled(valor);
        CmbFornecedor2.setEnabled(valor);
        LblFornec3.setEnabled(valor);
        CmbFornecedor3.setEnabled(valor);
        LblUniMed.setEnabled(valor);
        CmbUniMed.setEnabled(valor);
        LblAtivo.setEnabled(valor);
        ChkAtivo.setEnabled(valor);
        LblPrecoVenda.setEnabled(valor);
        FTxtPrecoVenda.setEnabled(valor);
        LblPrecoCusto.setEnabled(valor);
        FTxtPrecoCusto.setEnabled(valor);
        LblDevVendas.setEnabled(valor);
        FTxtDevVendas.setEnabled(valor);
        LblAbatVendas.setEnabled(valor);
        FTxtAbatVendas.setEnabled(valor);
        LblComisVendas.setEnabled(valor);
        FTxtComVendas.setEnabled(valor);
        LblIcms.setEnabled(valor);
        FTxtIcmsVendas.setEnabled(valor);
        LblIpi.setEnabled(valor);
        FTxtIpiVendas.setEnabled(valor);
        LblPis.setEnabled(valor);
        FTxtPisVendas.setEnabled(valor);
        LblCofins.setEnabled(valor);
        FTxtCofinsVendas.setEnabled(valor);
        LblSimples.setEnabled(valor);
        FTxtSimplesVendas.setEnabled(valor);
        LblIss.setEnabled(valor);
        FTxtIssVendas.setEnabled(valor);
        LblIr.setEnabled(valor);
        FTxtIrVendas.setEnabled(valor);
        LblCsll.setEnabled(valor);
        FTxtCsllVendas.setEnabled(valor);
        LblEmbalagem.setEnabled(valor);
        FTxtEmbalagem.setEnabled(valor);
        LblFrete.setEnabled(valor);
        FTxtFrete.setEnabled(valor);
        LblInsumos.setEnabled(valor);
        FTxtOutrosInsumos.setEnabled(valor);
        LblMargem.setEnabled(valor);
        FTxtMargemContrib.setEnabled(valor);
        LblNcm.setEnabled(valor);
        TxtNcm.setEnabled(valor);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cad_Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cad_Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cad_Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cad_Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cad_Produto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnInserirAlterar;
    private javax.swing.JButton BtnPesquisar;
    private javax.swing.JButton BtnSair;
    private javax.swing.JCheckBox ChkAtivo;
    private javax.swing.JComboBox<String> CmbFornecedor1;
    private javax.swing.JComboBox<String> CmbFornecedor2;
    private javax.swing.JComboBox<String> CmbFornecedor3;
    private javax.swing.JComboBox<String> CmbGrupo;
    private javax.swing.JComboBox<String> CmbUniMed;
    private javax.swing.JFormattedTextField FTxtAbatVendas;
    private javax.swing.JFormattedTextField FTxtCofinsVendas;
    private javax.swing.JFormattedTextField FTxtComVendas;
    private javax.swing.JFormattedTextField FTxtCsllVendas;
    private javax.swing.JFormattedTextField FTxtDevVendas;
    private javax.swing.JFormattedTextField FTxtEmbalagem;
    private javax.swing.JFormattedTextField FTxtFrete;
    private javax.swing.JFormattedTextField FTxtIcmsVendas;
    private javax.swing.JFormattedTextField FTxtIpiVendas;
    private javax.swing.JFormattedTextField FTxtIrVendas;
    private javax.swing.JFormattedTextField FTxtIssVendas;
    private javax.swing.JFormattedTextField FTxtMargemContrib;
    private javax.swing.JFormattedTextField FTxtOutrosInsumos;
    private javax.swing.JFormattedTextField FTxtPisVendas;
    private javax.swing.JFormattedTextField FTxtPrecoCusto;
    private javax.swing.JFormattedTextField FTxtPrecoVenda;
    private javax.swing.JFormattedTextField FTxtSimplesVendas;
    private javax.swing.JLabel LblAbatVendas;
    private javax.swing.JLabel LblAtivo;
    private javax.swing.JLabel LblCodigo;
    private javax.swing.JLabel LblCofins;
    private javax.swing.JLabel LblComisVendas;
    private javax.swing.JLabel LblCsll;
    private javax.swing.JLabel LblDescricao;
    private javax.swing.JLabel LblDevVendas;
    private javax.swing.JLabel LblEmbalagem;
    private javax.swing.JLabel LblFornec1;
    private javax.swing.JLabel LblFornec2;
    private javax.swing.JLabel LblFornec3;
    private javax.swing.JLabel LblFrete;
    private javax.swing.JLabel LblGrupo;
    private javax.swing.JLabel LblIcms;
    private javax.swing.JLabel LblInsumos;
    private javax.swing.JLabel LblIpi;
    private javax.swing.JLabel LblIr;
    private javax.swing.JLabel LblIss;
    private javax.swing.JLabel LblMargem;
    private javax.swing.JLabel LblNcm;
    private javax.swing.JLabel LblPis;
    private javax.swing.JLabel LblPrecoCusto;
    private javax.swing.JLabel LblPrecoVenda;
    private javax.swing.JLabel LblSimples;
    private javax.swing.JLabel LblUniMed;
    private javax.swing.JTextField TxtCodigo;
    private javax.swing.JTextField TxtDescricao;
    private javax.swing.JTextField TxtNcm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
